"""PostgreSQL-backed run storage.

Implements :class:`~orchestrator.workflow.store.RunStore` per
``docs/SYSTEM_ARCHITECTURE.md``: PostgreSQL holds workflow runs, events and artifact
metadata; the artifact store stays on the local filesystem. So artifact payloads and
worker logs are still files, and this class records where they are and what they
hashed to.

Used through psycopg directly rather than an ORM. There are three tables, the record is
already a versioned pydantic model that goes in as JSONB, and an ORM plus a migration
tool would be more moving parts than the schema justifies.

The schema is created on demand and is idempotent, so pointing at an empty database is
all the setup there is.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import psycopg
from psycopg.types.json import Jsonb

from orchestrator.workflow.store import RunEvent, RunRecord, RunStore, RunStoreError

SCHEMA = """
CREATE TABLE IF NOT EXISTS runs (
    run_id           TEXT PRIMARY KEY,
    task_id          TEXT        NOT NULL,
    workflow_id      TEXT        NOT NULL,
    workflow_version TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    task_state       TEXT        NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- The record verbatim. Columns above are promoted only for the queries this store
    -- actually runs, so adding a RunRecord field does not need a migration.
    record           JSONB       NOT NULL
);

CREATE TABLE IF NOT EXISTS run_events (
    -- Identity rather than a timestamp for ordering: two events in the same
    -- millisecond must still read back in the order they were appended.
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id  TEXT        NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    at      TIMESTAMPTZ NOT NULL,
    kind    TEXT        NOT NULL,
    node_id TEXT,
    detail  JSONB       NOT NULL
);

CREATE INDEX IF NOT EXISTS run_events_by_run ON run_events (run_id, id);

CREATE TABLE IF NOT EXISTS run_artifacts (
    run_id     TEXT        NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    path       TEXT        NOT NULL,
    sha256     TEXT        NOT NULL,
    written_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id, name)
);
"""


def normalize_dsn(database_url: str) -> str:
    """Strip a SQLAlchemy driver suffix so psycopg can parse the URL.

    ``.env`` ships ``postgresql+psycopg://…``, which is SQLAlchemy's spelling. psycopg
    rejects it, and silently connecting to something else would be worse than saying so.
    """
    scheme, separator, rest = database_url.partition("://")
    if not separator:
        raise RunStoreError(f"not a database URL: {database_url}")
    return f"{scheme.split('+', 1)[0]}{separator}{rest}"


class PostgresRunStore(RunStore):
    def __init__(self, database_url: str, run_root: Path) -> None:
        self.dsn = normalize_dsn(database_url)
        self.run_root = run_root.expanduser().resolve()
        self._ensure_schema()

    def _connect(self) -> psycopg.Connection[Any]:
        try:
            return psycopg.connect(self.dsn, autocommit=True)
        except psycopg.Error as exc:
            raise RunStoreError(f"cannot reach the run database: {exc}") from exc

    def _ensure_schema(self) -> None:
        with self._connect() as connection:
            connection.execute(SCHEMA)

    # -- record ------------------------------------------------------------------

    def create(self, record: RunRecord) -> RunRecord:
        # The directories exist whatever the backend: workers write files into them.
        self.artifact_dir(record.run_id).mkdir(parents=True, exist_ok=True)
        self.log_dir(record.run_id).mkdir(parents=True, exist_ok=True)
        with self._connect() as connection:
            try:
                connection.execute(
                    """
                    INSERT INTO runs
                        (run_id, task_id, workflow_id, workflow_version,
                         created_at, task_state, record)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        record.run_id,
                        record.task_id,
                        record.workflow_id,
                        record.workflow_version,
                        record.created_at,
                        record.task_state.value,
                        Jsonb(record.model_dump(mode="json")),
                    ),
                )
            except psycopg.errors.UniqueViolation as exc:
                raise RunStoreError(f"run {record.run_id} already exists") from exc
        return record

    def load(self, run_id: str) -> RunRecord:
        with self._connect() as connection:
            row = connection.execute(
                "SELECT record FROM runs WHERE run_id = %s", (run_id,)
            ).fetchone()
        if row is None:
            raise RunStoreError(f"no such run: {run_id}")
        try:
            return RunRecord.model_validate(row[0])
        except ValueError as exc:
            raise RunStoreError(f"run {run_id} has an unreadable record: {exc}") from exc

    def save(self, record: RunRecord) -> None:
        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO runs
                    (run_id, task_id, workflow_id, workflow_version,
                     created_at, task_state, record)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (run_id) DO UPDATE SET
                    task_state = EXCLUDED.task_state,
                    record     = EXCLUDED.record,
                    updated_at = now()
                """,
                (
                    record.run_id,
                    record.task_id,
                    record.workflow_id,
                    record.workflow_version,
                    record.created_at,
                    record.task_state.value,
                    Jsonb(record.model_dump(mode="json")),
                ),
            )

    def list_runs(self) -> tuple[RunRecord, ...]:
        with self._connect() as connection:
            rows = connection.execute(
                "SELECT record FROM runs ORDER BY created_at DESC, run_id DESC"
            ).fetchall()
        records: list[RunRecord] = []
        for (payload,) in rows:
            try:
                records.append(RunRecord.model_validate(payload))
            except ValueError:
                # One unreadable record must not hide the rest of the listing.
                continue
        return tuple(records)

    # -- artifacts ---------------------------------------------------------------

    def write_artifact(self, run_id: str, filename: str, payload: Any) -> Path:
        path = self.artifact_path(run_id, filename)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = json.dumps(payload, indent=2, ensure_ascii=False)
        path.write_text(body, encoding="utf-8")

        digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO run_artifacts (run_id, name, path, sha256, written_at)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (run_id, name) DO UPDATE SET
                    path = EXCLUDED.path,
                    sha256 = EXCLUDED.sha256,
                    written_at = EXCLUDED.written_at
                """,
                (run_id, filename, str(path), digest, datetime.now(UTC)),
            )
        return path

    def read_artifact(self, run_id: str, filename: str) -> Any:
        path = self.artifact_path(run_id, filename)
        if not path.is_file():
            raise RunStoreError(f"missing artifact {filename} in run {run_id}")
        body = path.read_text(encoding="utf-8")

        expected = self.artifact_digest(run_id, filename)
        if expected is not None:
            actual = hashlib.sha256(body.encode("utf-8")).hexdigest()
            if actual != expected:
                # The metadata and the file disagree. Reporting the content as if it
                # were the recorded artifact would launder an unexplained change.
                raise RunStoreError(
                    f"artifact {filename} in run {run_id} does not match its recorded "
                    f"sha256 ({actual} != {expected})"
                )
        try:
            return json.loads(body)
        except json.JSONDecodeError as exc:
            raise RunStoreError(f"artifact {filename} in run {run_id} is not JSON: {exc}") from exc

    def artifact_digest(self, run_id: str, filename: str) -> str | None:
        with self._connect() as connection:
            row = connection.execute(
                "SELECT sha256 FROM run_artifacts WHERE run_id = %s AND name = %s",
                (run_id, filename),
            ).fetchone()
        return row[0] if row else None

    # -- events ------------------------------------------------------------------

    def append_event(self, run_id: str, event: RunEvent) -> None:
        with self._connect() as connection:
            connection.execute(
                """
                INSERT INTO run_events (run_id, at, kind, node_id, detail)
                VALUES (%s, %s, %s, %s, %s)
                """,
                (run_id, event.at, event.kind, event.node_id, Jsonb(event.detail)),
            )

    def read_events(self, run_id: str) -> tuple[RunEvent, ...]:
        with self._connect() as connection:
            rows = connection.execute(
                """
                SELECT at, kind, node_id, detail
                FROM run_events WHERE run_id = %s ORDER BY id
                """,
                (run_id,),
            ).fetchall()
        return tuple(
            RunEvent(at=at.isoformat(), kind=kind, node_id=node_id, detail=detail)
            for at, kind, node_id, detail in rows
        )
