"""Probe definitions for the Milestone 1 CLI capability spike.

Each probe answers one question about one CLI, along the ten dimensions listed
in ``docs/START_HERE.md``. Flags used here come from the CLI's own ``--help``
output captured on this machine; nothing is assumed from vendor documentation.

Probes run in list order. Session-continuation probes depend on the probe
immediately before them, so do not reorder within a worker block.
"""

from __future__ import annotations

from spike_m1 import Probe

# Fixed so the resume probe can target the session the seed probe created.
CLAUDE_SESSION_ID = "3f1c0a7e-9b2d-4c81-a5e6-7d0f2b4a6c88"

# Kept tiny on purpose: these probes spend real subscription quota.
TINY_PROMPT = "Reply with exactly: OK. No other text."

_JSON_SCHEMA = (
    '{"type":"object","properties":{"verdict":{"type":"string"},'
    '"confidence":{"type":"number"}},"required":["verdict","confidence"],'
    '"additionalProperties":false}'
)


CLAUDE_PROBES: list[Probe] = [
    Probe(
        id="claude-version",
        worker="claude",
        dimension="installed version",
        question="What version is installed and does --version exit 0?",
        args=["--version"],
        timeout_s=30,
        expect="version string on stdout, exit 0",
    ),
    Probe(
        id="claude-auth-status",
        worker="claude",
        dimension="authentication mode",
        question="Which auth mode is active, and is it machine-readable?",
        args=["auth", "status"],
        timeout_s=30,
        expect="JSON with loggedIn/authMethod/subscriptionType",
    ),
    Probe(
        id="claude-doctor",
        worker="claude",
        dimension="authentication mode",
        question="Does the install report itself healthy without a trust prompt?",
        args=["doctor"],
        timeout_s=60,
        expect="health output, exit 0",
    ),
    Probe(
        id="claude-headless-text",
        worker="claude",
        dimension="headless invocation",
        question="Does -p run non-interactively with no TTY and no tools?",
        args=["-p", TINY_PROMPT, "--model", "sonnet", "--tools", "", "--output-format", "text"],
        timeout_s=120,
        expect="plain text answer on stdout, exit 0, no prompt for input",
    ),
    Probe(
        id="claude-headless-json",
        worker="claude",
        dimension="structured output",
        question="Does --output-format json give a parseable envelope with session id and cost?",
        args=["-p", TINY_PROMPT, "--model", "sonnet", "--tools", "", "--output-format", "json"],
        timeout_s=120,
        expect="single JSON object incl. session_id, is_error, total_cost_usd, num_turns",
    ),
    Probe(
        id="claude-json-schema",
        worker="claude",
        dimension="structured output",
        question="Does --json-schema constrain the final answer to our contract shape?",
        args=[
            "-p",
            "Judge this statement: 2+2=4. Answer with verdict and confidence.",
            "--model",
            "sonnet",
            "--tools",
            "",
            "--output-format",
            "json",
            "--json-schema",
            _JSON_SCHEMA,
        ],
        timeout_s=120,
        expect="result field conforms to the supplied schema",
    ),
    Probe(
        id="claude-stream-json",
        worker="claude",
        dimension="streaming logs",
        question="Does --output-format stream-json emit events incrementally, not at exit?",
        args=[
            "-p",
            "List the numbers 1 to 20, one per line, nothing else.",
            "--model",
            "sonnet",
            "--tools",
            "",
            "--output-format",
            "stream-json",
            "--verbose",
            "--include-partial-messages",
        ],
        timeout_s=120,
        expect="multiple JSONL events with a measurable arrival spread",
    ),
    Probe(
        id="claude-exit-bad-flag",
        worker="claude",
        dimension="exit code behaviour",
        question="What exit code does an invalid flag value produce?",
        args=["-p", "hi", "--output-format", "not-a-real-format"],
        timeout_s=30,
        expect="non-zero exit, error text on stderr",
    ),
    Probe(
        id="claude-exit-bad-model",
        worker="claude",
        dimension="exit code behaviour",
        question="Does a rejected model surface as a non-zero exit or a soft JSON error?",
        args=[
            "-p",
            TINY_PROMPT,
            "--model",
            "definitely-not-a-model",
            "--tools",
            "",
            "--output-format",
            "json",
        ],
        timeout_s=90,
        expect="either non-zero exit or is_error=true in the JSON envelope",
    ),
    Probe(
        id="claude-timeout-kill",
        worker="claude",
        dimension="timeout and cancellation",
        question="Can the supervisor kill a long run mid-flight and reclaim the tree?",
        args=[
            "-p",
            "Write a 2000 word essay about the history of the bicycle.",
            "--model",
            "sonnet",
            "--tools",
            "",
            "--output-format",
            "stream-json",
            "--verbose",
        ],
        timeout_s=10,
        expect_timeout=True,
        expect="runner reports timed_out=true and kills the process group",
    ),
    Probe(
        id="claude-session-seed",
        worker="claude",
        dimension="session continuation",
        question="Can we pin a session id we choose, so the orchestrator owns the handle?",
        args=[
            "-p",
            "Remember this codeword: ORCHID. Reply with exactly: STORED.",
            "--session-id",
            CLAUDE_SESSION_ID,
            "--model",
            "sonnet",
            "--tools",
            "",
            "--output-format",
            "json",
        ],
        timeout_s=120,
        expect="exit 0, session_id in output equals the id we supplied",
    ),
    Probe(
        id="claude-session-resume",
        worker="claude",
        dimension="session continuation",
        question="Does --resume <id> actually carry prior turn state?",
        args=[
            "-p",
            "What was the codeword? Reply with just the word.",
            "--resume",
            CLAUDE_SESSION_ID,
            "--model",
            "sonnet",
            "--tools",
            "",
            "--output-format",
            "json",
        ],
        timeout_s=120,
        expect="answer contains ORCHID, proving state carried across processes",
    ),
    Probe(
        id="claude-scoped-write",
        worker="claude",
        dimension="scoped file writes",
        question="Does a write stay inside cwd when tools are restricted to Read/Write?",
        args=[
            "-p",
            "Create a file named spike_claude.txt in the current directory "
            "containing exactly HELLO. Then stop.",
            "--model",
            "sonnet",
            "--tools",
            "Read,Write",
            "--permission-mode",
            "acceptEdits",
            "--output-format",
            "json",
        ],
        timeout_s=180,
        expect="spike_claude.txt appears in the sandbox only",
    ),
    Probe(
        id="claude-escape-attempt",
        worker="claude",
        dimension="scoped file writes",
        question="Is a write outside cwd refused without --add-dir?",
        args=[
            "-p",
            "Create a file at ../spike_escape.txt containing ESCAPED. "
            "If you cannot, say BLOCKED and stop.",
            "--model",
            "sonnet",
            "--tools",
            "Read,Write",
            "--permission-mode",
            "acceptEdits",
            "--output-format",
            "json",
        ],
        timeout_s=180,
        expect="no file created above the sandbox",
    ),
    Probe(
        id="claude-auth-failure",
        worker="claude",
        dimension="auth or quota failure",
        question="How does a bad credential fail: exit code, stderr, or soft JSON error?",
        args=["-p", TINY_PROMPT, "--bare", "--tools", "", "--output-format", "json"],
        env={"ANTHROPIC_API_KEY": "sk-ant-invalid-key-for-spike-testing-000000"},
        timeout_s=90,
        expect="distinguishable auth failure signal the adapter can classify",
    ),
]


CODEX_PROBES: list[Probe] = [
    Probe(
        id="codex-version",
        worker="codex",
        dimension="installed version",
        question="What version is installed and does --version exit 0?",
        args=["--version"],
        timeout_s=30,
        expect="version string on stdout, exit 0",
    ),
    Probe(
        id="codex-login-status",
        worker="codex",
        dimension="authentication mode",
        question="Which auth mode is active (ChatGPT subscription vs API key)?",
        args=["login", "status"],
        timeout_s=30,
        expect="auth mode reported, exit 0",
    ),
    Probe(
        id="codex-doctor",
        worker="codex",
        dimension="authentication mode",
        question="Does codex doctor report install, config, auth and runtime health?",
        args=["doctor"],
        timeout_s=90,
        expect="diagnostic report, exit 0",
    ),
    Probe(
        id="codex-headless-text",
        worker="codex",
        dimension="headless invocation",
        question="Does codex exec run non-interactively under read-only sandbox?",
        args=["exec", "-s", "read-only", "--color", "never", TINY_PROMPT],
        timeout_s=180,
        expect="answer on stdout, exit 0, no approval prompt",
    ),
    Probe(
        id="codex-headless-json",
        worker="codex",
        dimension="structured output",
        question="Does --json produce parseable JSONL events?",
        args=[
            "exec",
            "--json",
            "-s",
            "read-only",
            "--color",
            "never",
            TINY_PROMPT,
        ],
        timeout_s=180,
        expect="one JSON object per line, terminal event identifiable",
    ),
    Probe(
        id="codex-output-schema",
        worker="codex",
        dimension="structured output",
        question="Does --output-schema constrain the final message to our contract shape?",
        args=[
            "exec",
            "-s",
            "read-only",
            "--color",
            "never",
            "--output-schema",
            "spike-schema.json",
            "--output-last-message",
            "spike-last-message.txt",
            "Judge this statement: 2+2=4. Answer with verdict and confidence.",
        ],
        timeout_s=180,
        expect="spike-last-message.txt holds JSON matching the schema",
    ),
    Probe(
        id="codex-streaming",
        worker="codex",
        dimension="streaming logs",
        question="Do --json events arrive incrementally rather than all at exit?",
        args=[
            "exec",
            "--json",
            "-s",
            "read-only",
            "--color",
            "never",
            "List the numbers 1 to 20, one per line, nothing else.",
        ],
        timeout_s=180,
        expect="multiple events with a measurable arrival spread",
    ),
    Probe(
        id="codex-exit-bad-flag",
        worker="codex",
        dimension="exit code behaviour",
        question="What exit code does an invalid flag value produce?",
        args=["exec", "-s", "not-a-real-sandbox", "hi"],
        timeout_s=30,
        expect="non-zero exit, clap error on stderr",
    ),
    Probe(
        id="codex-exit-bad-model",
        worker="codex",
        dimension="exit code behaviour",
        question="Does a rejected model surface as non-zero exit?",
        args=[
            "exec",
            "-m",
            "definitely-not-a-model",
            "-s",
            "read-only",
            "--color",
            "never",
            TINY_PROMPT,
        ],
        timeout_s=120,
        expect="non-zero exit with a classifiable error",
    ),
    Probe(
        id="codex-timeout-kill",
        worker="codex",
        dimension="timeout and cancellation",
        question="Can the supervisor kill a long run mid-flight and reclaim the tree?",
        args=[
            "exec",
            "--json",
            "-s",
            "read-only",
            "--color",
            "never",
            "Write a 2000 word essay about the history of the bicycle.",
        ],
        timeout_s=12,
        expect_timeout=True,
        expect="runner reports timed_out=true and kills the node + rust child tree",
    ),
    Probe(
        id="codex-session-seed",
        worker="codex",
        dimension="session continuation",
        question="Does a persisted session exist after a non-ephemeral exec run?",
        args=[
            "exec",
            "--json",
            "-s",
            "read-only",
            "--color",
            "never",
            "Remember this codeword: ORCHID. Reply with exactly: STORED.",
        ],
        timeout_s=180,
        expect="session/thread id present in the JSONL event stream",
    ),
    Probe(
        id="codex-session-resume",
        worker="codex",
        dimension="session continuation",
        question="Does exec resume --last carry prior turn state?",
        args=[
            # `codex exec resume` has a narrower flag surface than `codex exec`:
            # no -s/--sandbox and no --color. Observed from `exec resume --help`.
            "exec",
            "resume",
            "--last",
            "--json",
            "What was the codeword? Reply with just the word.",
        ],
        timeout_s=180,
        expect="answer contains ORCHID",
    ),
    Probe(
        id="codex-scoped-write",
        worker="codex",
        dimension="scoped file writes",
        question="Does workspace-write confine edits to the workspace root?",
        args=[
            "exec",
            "-s",
            "workspace-write",
            "--color",
            "never",
            "Create a file named spike_codex.txt in the current directory "
            "containing exactly HELLO. Then stop.",
        ],
        timeout_s=240,
        expect="spike_codex.txt appears in the sandbox only",
    ),
    Probe(
        id="codex-escape-attempt",
        worker="codex",
        dimension="scoped file writes",
        question="Is a write above the workspace root refused under workspace-write?",
        args=[
            "exec",
            "-s",
            "workspace-write",
            "--color",
            "never",
            "Create a file at ../spike_escape_codex.txt containing ESCAPED. "
            "If you cannot, say BLOCKED and stop.",
        ],
        timeout_s=240,
        expect="no file created above the sandbox",
    ),
    Probe(
        id="codex-auth-failure",
        worker="codex",
        dimension="auth or quota failure",
        question="How does a missing credential store fail?",
        args=[
            "exec",
            "--json",
            "-s",
            "read-only",
            "--color",
            "never",
            "--ignore-user-config",
            TINY_PROMPT,
        ],
        env={"CODEX_HOME": "spike-empty-codex-home"},
        timeout_s=90,
        expect="distinguishable auth failure signal the adapter can classify",
    ),
]


PROBES: list[Probe] = [*CLAUDE_PROBES, *CODEX_PROBES]
